/**
 * Copyright (c) 2026 DevSeeker Contributors
 *
 * MIT License - see LICENSE file for details
 */

/**
 * ErrorCodes 冻结枚举
 *
 * 来源：docs/SPEC/error-model.md §3
 * 规则：
 * - 格式 DOMAIN.CATEGORY.SPECIFIC（三段全大写 + 下划线）
 * - 新增错误码必须同步 CHANGELOG_OF_DESIGN.md（minor）
 * - 删除/改名必须走 ADR（major 破坏性）
 *
 * 当前版本：v1.3.3 初版 74 条
 */

export const ErrorCodes = {
  // ─────────── M1 PROVIDER ───────────
  PROVIDER_AUTH_INVALID_API_KEY: 'PROVIDER.AUTH.INVALID_API_KEY',
  PROVIDER_AUTH_EXPIRED: 'PROVIDER.AUTH.EXPIRED',
  PROVIDER_AUTH_INSUFFICIENT_QUOTA: 'PROVIDER.AUTH.INSUFFICIENT_QUOTA',
  PROVIDER_NET_TIMEOUT: 'PROVIDER.NET.TIMEOUT',
  PROVIDER_NET_UNREACHABLE: 'PROVIDER.NET.UNREACHABLE',
  PROVIDER_RATE_LIMITED: 'PROVIDER.NET.RATE_LIMITED',
  /** 每日配额耗尽（如 OpenRouter free-models-per-day），不可重试，应立即 failover */
  PROVIDER_DAILY_QUOTA_EXCEEDED: 'PROVIDER.NET.DAILY_QUOTA_EXCEEDED',
  PROVIDER_SERVER_5XX: 'PROVIDER.NET.SERVER_5XX',
  PROVIDER_RESP_INVALID_JSON: 'PROVIDER.RESP.INVALID_JSON',
  PROVIDER_RESP_CONTEXT_OVERFLOW: 'PROVIDER.RESP.CONTEXT_OVERFLOW',
  PROVIDER_RESP_CONTENT_FILTERED: 'PROVIDER.RESP.CONTENT_FILTERED',
  PROVIDER_STREAM_BROKEN: 'PROVIDER.STREAM.BROKEN',
  PROVIDER_MODEL_NOT_FOUND: 'PROVIDER.MODEL.NOT_FOUND',
  /** HTTP 529 / server overloaded（P0-5 新增，对齐 FailoverReason） */
  PROVIDER_SERVER_OVERLOADED: 'PROVIDER.NET.OVERLOADED',
  /** HTTP 402 / billing insufficient quota（P0-5 新增） */
  PROVIDER_BILLING_INSUFFICIENT: 'PROVIDER.BILLING.INSUFFICIENT',
  /** 会话过期 / token expired（P0-5 新增） */
  PROVIDER_AUTH_SESSION_EXPIRED: 'PROVIDER.AUTH.SESSION_EXPIRED',
  /** HTTP 400 但非 context_overflow / content_filtered — 不可重试（消息格式错误等） */
  PROVIDER_BAD_REQUEST: 'PROVIDER.BAD_REQUEST',

  // ─────────── M2 ROUTER ───────────
  ROUTER_NO_MATCH: 'ROUTER.SELECT.NO_MATCH',
  ROUTER_ALL_PROVIDERS_DOWN: 'ROUTER.SELECT.ALL_DOWN',

  // ─────────── M3 PROMPT ───────────
  PROMPT_TEMPLATE_MISSING: 'PROMPT.BUILD.TEMPLATE_MISSING',
  PROMPT_CONTEXT_OVERFLOW: 'PROMPT.BUILD.CONTEXT_OVERFLOW',
  PROMPT_RENDER_FAIL: 'PROMPT.BUILD.RENDER_FAIL',

  // ─────────── M4 INDEX ───────────
  INDEX_NOT_READY: 'INDEX.STATE.NOT_READY',
  INDEX_DB_CORRUPTED: 'INDEX.DB.CORRUPTED',
  INDEX_DB_WRITE_FAIL: 'INDEX.DB.WRITE_FAIL',
  INDEX_EMBED_TIMEOUT: 'INDEX.EMBED.TIMEOUT',
  INDEX_EMBED_RATE_LIMITED: 'INDEX.EMBED.RATE_LIMITED',
  INDEX_EMBED_INPUT_TOO_LONG: 'INDEX.EMBED.INPUT_TOO_LONG',
  INDEX_EMBEDDER_UNAVAILABLE: 'INDEX.EMBED.UNAVAILABLE',
  INDEX_PARSE_FAIL: 'INDEX.PARSE.FAIL',
  /** W14.1 · 知识库目录不存在或不可访问（软失败，由工具层给用户引导） */
  KNOWLEDGE_BASE_EMPTY: 'INDEX.KB.EMPTY',

  // ─────────── M5 LSP ───────────
  LSP_SERVER_NOT_RUNNING: 'LSP.SERVER.NOT_RUNNING',
  LSP_OPERATION_UNSUPPORTED: 'LSP.OP.UNSUPPORTED',
  LSP_TIMEOUT: 'LSP.OP.TIMEOUT',
  LSP_LOCATION_INVALID: 'LSP.OP.LOCATION_INVALID',

  // ─────────── M6 MEMORY ───────────
  MEMORY_CATEGORY_NOT_WRITABLE: 'MEMORY.WRITE.NOT_WRITABLE',
  MEMORY_CATEGORY_INVALID: 'MEMORY.WRITE.CATEGORY_INVALID',
  MEMORY_ID_NOT_FOUND: 'MEMORY.WRITE.ID_NOT_FOUND',
  MEMORY_STORE_CORRUPTED: 'MEMORY.STORE.CORRUPTED',
  MEMORY_SEARCH_INVALID_DEPTH: 'MEMORY.SEARCH.INVALID_DEPTH',

  // ─────────── M7 TASK ───────────
  TASK_MODE_TRANSITION_DENIED: 'TASK.MODE.TRANSITION_DENIED',
  TASK_LOOP_ABORTED: 'TASK.LOOP.ABORTED',
  TASK_LOOP_INFINITE: 'TASK.LOOP.INFINITE',
  TASK_BUDGET_EXCEEDED: 'TASK.BUDGET.EXCEEDED',

  // ─────────── M8 SUBAGENT ───────────
  SUBAGENT_INVOCATION_INVALID: 'SUBAGENT.SPAWN.INVOCATION_INVALID',
  SUBAGENT_LIMIT_EXCEEDED: 'SUBAGENT.SPAWN.LIMIT_EXCEEDED',
  SUBAGENT_NESTED_NOT_ALLOWED: 'SUBAGENT.SPAWN.NESTED',
  SUBAGENT_BUDGET_EXCEEDED_TOKEN: 'SUBAGENT.BUDGET.TOKEN',
  SUBAGENT_BUDGET_EXCEEDED_WALLCLOCK: 'SUBAGENT.BUDGET.WALLCLOCK',
  SUBAGENT_BUDGET_EXCEEDED_TOOLCALL: 'SUBAGENT.BUDGET.TOOLCALL',
  SUBAGENT_TOOL_NOT_ALLOWED: 'SUBAGENT.TOOL.NOT_ALLOWED',
  SUBAGENT_INTERRUPTED_BY_RESTART: 'SUBAGENT.LIFECYCLE.INTERRUPTED',
  SUBAGENT_FAILED: 'SUBAGENT.LIFECYCLE.FAILED',

  // ─────────── M9 TOOL ───────────
  TOOL_NOT_FOUND: 'TOOL.REGISTRY.NOT_FOUND',
  TOOL_ARGS_INVALID: 'TOOL.ARGS.INVALID',
  TOOL_ARGS_INVALID_JSON: 'TOOL.ARGS.INVALID_JSON',
  TOOL_ARGS_MISSING_REQUIRED: 'TOOL.ARGS.MISSING_REQUIRED',
  TOOL_EXEC_TIMEOUT: 'TOOL.EXEC.TIMEOUT',
  TOOL_EXEC_PERMISSION_DENIED: 'TOOL.EXEC.PERMISSION_DENIED',
  TOOL_EXEC_UNSAFE_BLOCKED: 'TOOL.EXEC.UNSAFE_BLOCKED',
  TOOL_EXEC_FAILED: 'TOOL.EXEC.FAILED',
  TOOL_PATH_INVALID: 'TOOL.PATH.INVALID',
  TOOL_PATCH_UNIQUE_FAIL: 'TOOL.PATCH.UNIQUE_FAIL',
  TOOL_PATCH_NO_MATCH: 'TOOL.PATCH.NO_MATCH',
  /** §8.11.2 · 文件已被外部修改，需先 read_file 取最新内容 */
  TOOL_PATCH_CONFLICT: 'TOOL.PATCH.CONFLICT',
  /** 沙箱升级被用户拒绝（W9.13） */
  TOOL_SANDBOX_ESCALATION_DENIED: 'TOOL.SANDBOX.ESCALATION_DENIED',
  /** 沙箱内命令命中 SANDBOXING 失败（W9.13 hint） */
  TOOL_SANDBOXING_DETECTED: 'TOOL.SANDBOX.SANDBOXING_DETECTED',

  // ─────────── M10 CONTEXT ───────────
  CONTEXT_ATTACHMENT_TOO_LARGE: 'CONTEXT.ATTACH.TOO_LARGE',
  CONTEXT_ATTACHMENT_INVALID_TYPE: 'CONTEXT.ATTACH.INVALID_TYPE',

  // ─────────── M11 UI ───────────
  UI_WEBVIEW_DISCONNECTED: 'UI.WEBVIEW.DISCONNECTED',
  UI_RENDER_FAIL: 'UI.RENDER.FAIL',

  // ─────────── M12 WEB ───────────
  WEB_SEARCH_PROVIDER_DOWN: 'WEB.SEARCH.PROVIDER_DOWN',
  WEB_FETCH_TIMEOUT: 'WEB.FETCH.TIMEOUT',
  WEB_FETCH_403: 'WEB.FETCH.FORBIDDEN',
  WEB_FETCH_404: 'WEB.FETCH.NOT_FOUND',
  WEB_URL_BLOCKED_BY_WHITELIST: 'WEB.URL.BLOCKED',
  WEB_FETCH_PDF_UNSUPPORTED: 'WEB.FETCH.PDF_UNSUPPORTED',
  WEB_FETCH_RATE_LIMITED: 'WEB.FETCH.RATE_LIMITED',

  // ─────────── M13 RULES ───────────
  RULES_FILE_PARSE_FAIL: 'RULES.LOAD.PARSE_FAIL',
  RULES_GLOB_INVALID: 'RULES.LOAD.GLOB_INVALID',
  RULES_REFERENCE_MISSING: 'RULES.FETCH.MISSING',

  // ─────────── M14 MCP ───────────
  MCP_SERVER_SPAWN_FAIL: 'MCP.SPAWN.FAIL',
  MCP_SERVER_HEALTH_FAIL: 'MCP.HEALTH.FAIL',
  MCP_PROTOCOL_VIOLATION: 'MCP.PROTO.VIOLATION',
  MCP_TOOL_CALL_FAIL: 'MCP.TOOL.FAIL',

  // ─────────── M15 CHECKPOINT ───────────
  CHECKPOINT_SAVE_FAIL: 'CHECKPOINT.SAVE.FAIL',
  CHECKPOINT_RESTORE_FAIL: 'CHECKPOINT.RESTORE.FAIL',
  CHECKPOINT_SHADOW_REPO_CORRUPT: 'CHECKPOINT.REPO.CORRUPT',

  // ─────────── HOOKS (W5) ───────────
  HOOK_CONFIG_PARSE_FAIL: 'HOOK.CONFIG.PARSE_FAIL',
  HOOK_COMMAND_TIMEOUT: 'HOOK.EXEC.TIMEOUT',
  HOOK_COMMAND_FAIL: 'HOOK.EXEC.FAIL',
  HOOK_DENIED: 'HOOK.DENIED',

  // ─────────── M16 COST ───────────
  COST_DB_WRITE_FAIL: 'COST.DB.WRITE_FAIL',

  // ─────────── M17 SESSION ───────────
  SESSION_CORRUPTED: 'SESSION.LOAD.CORRUPTED',
  SESSION_NOT_FOUND: 'SESSION.LOAD.NOT_FOUND',
  SESSION_WRITE_FAIL: 'SESSION.SAVE.WRITE_FAIL',

  // ─────────── CONFIG ───────────
  CONFIG_FILE_MISSING: 'CONFIG.LOAD.FILE_MISSING',
  CONFIG_BOM_DETECTED: 'CONFIG.LOAD.BOM',
  CONFIG_PARSE_FAIL: 'CONFIG.LOAD.PARSE_FAIL',
  CONFIG_SCHEMA_INVALID: 'CONFIG.LOAD.SCHEMA_INVALID',

  // ─────────── INTERNAL ───────────
  INTERNAL_ASSERTION_FAILED: 'INTERNAL.BUG.ASSERTION',
  INTERNAL_UNREACHABLE: 'INTERNAL.BUG.UNREACHABLE',
  INTERNAL_UNKNOWN: 'INTERNAL.BUG.UNKNOWN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type Severity = 'fatal' | 'error' | 'warn' | 'info';

export interface RetryPolicy {
  attempts: number;
  backoff: 'linear' | 'exp' | 'jitter';
  baseMs: number;
  maxMs?: number;
}

/**
 * 重试策略表（SPEC/error-model.md §4）
 * 未列出的错误码一律不重试。
 */
export const RETRY_TABLE: Partial<Record<ErrorCode, RetryPolicy>> = {
  [ErrorCodes.PROVIDER_NET_TIMEOUT]: { attempts: 3, backoff: 'jitter', baseMs: 1500 },
  [ErrorCodes.PROVIDER_NET_UNREACHABLE]: { attempts: 3, backoff: 'jitter', baseMs: 2000 },
  [ErrorCodes.PROVIDER_RATE_LIMITED]: { attempts: 5, backoff: 'jitter', baseMs: 2000, maxMs: 30000 },
  [ErrorCodes.PROVIDER_SERVER_5XX]: { attempts: 3, backoff: 'jitter', baseMs: 1000 },
  [ErrorCodes.PROVIDER_SERVER_OVERLOADED]: { attempts: 2, backoff: 'jitter', baseMs: 3000 },
  [ErrorCodes.PROVIDER_STREAM_BROKEN]: { attempts: 5, backoff: 'jitter', baseMs: 1500 },

  [ErrorCodes.INDEX_EMBED_TIMEOUT]: { attempts: 3, backoff: 'exp', baseMs: 1000 },
  [ErrorCodes.INDEX_EMBED_RATE_LIMITED]: { attempts: 5, backoff: 'exp', baseMs: 2000, maxMs: 30000 },
  [ErrorCodes.INDEX_DB_WRITE_FAIL]: { attempts: 2, backoff: 'linear', baseMs: 200 },

  [ErrorCodes.LSP_TIMEOUT]: { attempts: 2, backoff: 'linear', baseMs: 500 },
  [ErrorCodes.LSP_SERVER_NOT_RUNNING]: { attempts: 1, backoff: 'linear', baseMs: 3000 },

  [ErrorCodes.WEB_FETCH_TIMEOUT]: { attempts: 2, backoff: 'exp', baseMs: 1000 },
  [ErrorCodes.WEB_SEARCH_PROVIDER_DOWN]: { attempts: 2, backoff: 'exp', baseMs: 1000 },

  [ErrorCodes.MCP_SERVER_HEALTH_FAIL]: { attempts: 3, backoff: 'exp', baseMs: 2000 },

  [ErrorCodes.SESSION_WRITE_FAIL]: { attempts: 2, backoff: 'linear', baseMs: 200 },
  [ErrorCodes.CHECKPOINT_SAVE_FAIL]: { attempts: 2, backoff: 'linear', baseMs: 200 },
  [ErrorCodes.COST_DB_WRITE_FAIL]: { attempts: 2, backoff: 'linear', baseMs: 200 },
};

/**
 * 严重度表（SPEC/error-model.md §5）
 * 未列出的错误码默认 'error'。
 */
export const SEVERITY_TABLE: Partial<Record<ErrorCode, Severity>> = {
  [ErrorCodes.INDEX_DB_CORRUPTED]: 'fatal',
  [ErrorCodes.SESSION_CORRUPTED]: 'fatal',
  [ErrorCodes.CHECKPOINT_SHADOW_REPO_CORRUPT]: 'fatal',

  [ErrorCodes.PROVIDER_RATE_LIMITED]: 'warn',
  [ErrorCodes.PROVIDER_DAILY_QUOTA_EXCEEDED]: 'warn',
  [ErrorCodes.INDEX_EMBED_RATE_LIMITED]: 'warn',
  [ErrorCodes.INDEX_PARSE_FAIL]: 'warn',
  [ErrorCodes.LSP_TIMEOUT]: 'warn',
  [ErrorCodes.MEMORY_ID_NOT_FOUND]: 'warn',

  [ErrorCodes.CONFIG_BOM_DETECTED]: 'info',
  [ErrorCodes.SUBAGENT_BUDGET_EXCEEDED_TOKEN]: 'info',
};

export function getRetryPolicy(code: ErrorCode): RetryPolicy | undefined {
  return RETRY_TABLE[code];
}

export function getSeverity(code: ErrorCode): Severity {
  return SEVERITY_TABLE[code] ?? 'error';
}

export function isRetryable(code: ErrorCode): boolean {
  return RETRY_TABLE[code] !== undefined;
}
